name: Build spy-extension
on:
  push:
    branches: [ main ]
    paths: [ spy-extension/** ]
  workflow_dispatch:
  
jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Install dependencies
        working-directory: ./spy-extension
        run: yarn
        
      - name: Build main extension
        working-directory: ./spy-extension
        run: yarn build
      - name: Upload extension as Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: spy-extension
          path: ./spy-extension/dist
      
