name: OWASP Zap full-scan
on:
  workflow_dispatch:

permissions: write-all

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the Juice Shop webapplication
    steps:
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.4.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target: 'https://juice-shop.herokuapp.com/'
