name: Security Scan

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        scan-type: 'fs'
        format: 'sarif'
        output: 'trivy-results.sarif'
        vuln-type: 'os,library,vuln,secret,config'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@main
      continue-on-error: true
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
    - name: Run Bandit for azure-goat Python function
      continue-on-error: true
      uses: jpetrucciani/bandit-check@main
      with:
        path: './azure-goat/modules/module-1/resources/azure_function/data/app'
    - name: Upload report from Trivy as Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ScanReport
        path: 'trivy-results.sarif'
